# -*- coding: utf-8 -*-
"""SOL_Hands_On_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4MPw3qPLLNFLrq-hTop1dgBm_MzJjaC

<img src="https://www.insidehighered.com/sites/default/server_files/media/california_0.jpg">
The data pertains to the houses found in a given California district and some summary stats about them based on the 1990 census data. Be warned the data aren't cleaned so there are some preprocessing steps required! The columns are as follows, their names are pretty self explanitory

Acknowledgements:
This data was initially featured in the following paper:
Pace, R. Kelley, and Ronald Barry. "Sparse spatial autoregressions." Statistics & Probability Letters 33.3 (1997): 291-297.
"""

import pandas as pd

CA_url="https://raw.githubusercontent.com/csbfx/advpy122-data/master/California_housing.csv"

ca = pd.read_csv(CA_url)
ca.head()

"""### Q1. Create a plot that shows the relationship between `median_income` and `median_house_value` along with the `longitude` and `latitude`.

Derive meaningful conclusion out of it and write it in a textbox.
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
sns.relplot(
    data = ca,
    x= "longitude",
    y = "latitude",
    hue = 'median_house_value',
    size =  "median_income",
    sizes = (2, 250),
    palette = 'viridis'
)

plt.title ("Location of California Housing Based on Median House Value and Median Income", pad = 30);

"""The areas near the coast and the bay area are considered more expensive indicated by the yellow and green values of $400,000-500,000 for median house value. The median income significantly increases in those more expensive areas. The conclusion is that the higher the median house value, the more likely the people with an higher median income will live there **(A direct relationship between median house value and income)**. The longitude and latitude shows the location of the house values and the socioeconomic demographic of residents in California.

### Open-Ended Question: Explore additional relationships
Create an additional column in the `ca` dataframe with the column name `bedrooms_per_total_rooms`. This new column contains that values of `total_bedrooms` divided by `total_rooms`. Create a hexbin plot that shows the relationship between `median_house_value` and `bedrooms_per_total_rooms` where `bedrooms_per_total_rooms` is less than `0.5`. Include a meaningful title in the plot.

Derive a meaningful conclusion out of it and write it in a textbox.
"""

bedrooms_per_total_rooms = ca.total_bedrooms / ca.total_rooms
ca['bedrooms_per_total_rooms'] = bedrooms_per_total_rooms
ca

g= sns.jointplot(data= ca[(ca["bedrooms_per_total_rooms"] < 0.5)],
           x="bedrooms_per_total_rooms", y="median_house_value", kind="hex", gridsize = 30)
g.fig.suptitle("Bedrooms < 0.5 per total room along with Median House Value", y=1.05);

"""Most houses that contain less than 0.5 bedrooms per total room are in the 100,000 to 200,000 median house value range. The lower the median house value, the more likely there are less than 0.5 bedrooms in each house. This is a direct relationship. The outliers (around 0.15 at 500,000 median house value) shows a surprising value of less than 0.5 bedrooms in a high median house value household."""